test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: 	 	YOUR_CREDENTIAL_HERE
  PAYPAL_CLIENT_SECRET: 	YOUR_CREDENTIAL_HERE
  STRIPE_PUBLISHABLE_KEY:	pk_test_51HPjuoBdpYu2NwpzjH4kM17NNUOgu0elPUArTFu3cobdtUl0GzIRPJrsOHbc8QFYmlzcNpBU4wf7gRE5wODjO6Qf00fIZGpw7K
  STRIPE_SECRET_KEY: 	sk_test_51HPjuoBdpYu2NwpzgIiv4pLZ8L1RLRqKLsp8AYs5cIW3NR4IwBBAYnbdUU3vUIjBhRFqotnLrszNv41ph5G7odPd00wbNx8zni

development:
  <<: *default